CREATE DATABASE IF NOT EXISTS CampusLove;
USE CampusLove;

CREATE TABLE IF NOT EXISTS infoPersonal(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Edad INT NOT NULL,
    Genero VARCHAR(100) NOT NULL,
    Carrera VARCHAR(100) NOT NULL, 
    Intereses VARCHAR(100) NOT NULL UNIQUE,
    Frase VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    NombreUsuario VARCHAR(50) NOT NULL UNIQUE,
    Contrasena VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS Maches();
